### PR TITLE
Rajkumar

### PR DESCRIPTION
**Pull request by rajkumardongre**

### CODE REVIEW

**Comment by tusharkhatriofficial** [comment]
Is this tested? Once the URL is uploaded... each `posts` document must look like this

```
{
"_id" : ObjectId("630b6359992a9a108a748522"),
"title": "Blog title here",
"postFeaturedImage": "URL of the Image uploaded to firebase",
"content": "blog content",
}
```
> Please add your name to the contributor's list present in the README.md

**Comment by rajkumardongre** [comment]
> Is this tested? Once the URL is uploaded... each `posts` document must look like this
> 
> ```
> {
> "_id" : ObjectId("630b6359992a9a108a748522"),
> "title": "Blog title here",
> "postFeaturedImage": "URL of the Image uploaded to firebase",
> "content": "blog content",
> }
> ```
> 
> > Please add your name to the contributor's list present in the README.md

**Comment by rajkumardongre** [comment]
Yes i have check it is working as you mention, and i also added my name in contributor list

**Review by tusharkhatriofficial — APPROVED** [review]

**Review by tusharkhatriofficial — APPROVED** [review]

**Review by tusharkhatriofficial — APPROVED** [review]

**Comment by tusharkhatriofficial** [comment]
Can't really see anything happening... clicking on Publish does pretty much nothing! Could you please sort out the issue.

Screenshot 2022-10-06 at 9 22 43 PM


Screenshot 2022-10-06 at 9 23 10 PM

Screenshot 2022-10-06 at 9 24 08 PM

**Comment by tusharkhatriofficial** [comment]
I would suggest you write most of your code on server... also use `firebase-admin` SDK  to do the job. I'm leaving you a link where you can find step by step documentation to do so!

https://piyushgarg.dev/uploading-images-to-firebase-storage-with-nodejs

**Comment by rajkumardongre** [comment]
> I would suggest you write most of your code on server... also use `firebase-admin` SDK to do the job. I'm leaving you a link where you can find step by step documentation to do so!
> 
> https://piyushgarg.dev/uploading-images-to-firebase-storage-with-nodejs

Click Here
res1
Then make sure it is true
res2

**Comment by tusharkhatriofficial** [comment]
Gr8! It works now, I'll update the docs.

Screenshot 2022-10-07 at 2 38 08 PM

**Comment by rajkumardongre** [comment]
Really apologize for that, somehow I forgot to add that in doc

**Comment by rajkumardongre** [comment]
Don't worry I will make the changes in doc

**Comment by tusharkhatriofficial** [comment]
Please don't mind. Thanks for working on this :)

**Pull request merged**
